"""add estimated_rent to deal

Revision ID: 2451d1770fd3
Revises: c1cb9c096002
Create Date: 2026-04-03 20:07:32.152159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2451d1770fd3'
down_revision: Union[str, Sequence[str], None] = 'c1cb9c096002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deal', sa.Column('estimated_rent', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deal', 'estimated_rent')
    # ### end Alembic commands ###
