"""add agency_id to user and assigned_to to lead

Revision ID: 332dbbb934fd
Revises: 7c738a4cda96
Create Date: 2026-04-03 20:41:33.921267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '332dbbb934fd'
down_revision: Union[str, Sequence[str], None] = '7c738a4cda96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lead', sa.Column('assigned_to', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'lead', 'user', ['assigned_to'], ['id'])
    op.add_column('user', sa.Column('agency_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'agency', ['agency_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'agency_id')
    op.drop_constraint(None, 'lead', type_='foreignkey')
    op.drop_column('lead', 'assigned_to')
    # ### end Alembic commands ###
