"""add_vertical_and_auto_fields_to_deal

Revision ID: 4f72017327b0
Revises: fefc144a426c
Create Date: 2026-04-15 14:52:44.476973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f72017327b0'
down_revision: Union[str, Sequence[str], None] = 'fefc144a426c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deal', sa.Column('vertical', sa.String(), nullable=False, server_default='immo'))
    op.add_column('deal', sa.Column('brand', sa.String(), nullable=True))
    op.add_column('deal', sa.Column('model_name', sa.String(), nullable=True))
    op.add_column('deal', sa.Column('mileage', sa.Integer(), nullable=True))
    op.add_column('deal', sa.Column('year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deal', 'year')
    op.drop_column('deal', 'mileage')
    op.drop_column('deal', 'model_name')
    op.drop_column('deal', 'brand')
    op.drop_column('deal', 'vertical')
    # ### end Alembic commands ###
