"""add_agency_api_keys

Revision ID: 6440dba64c97
Revises: 82e92e77ba07
Create Date: 2026-04-19 21:24:38.135850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6440dba64c97'
down_revision: Union[str, Sequence[str], None] = '82e92e77ba07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agency', sa.Column('sms_api_key', sa.String(), nullable=True))
    op.add_column('agency', sa.Column('email_api_key', sa.String(), nullable=True))
    op.alter_column('agency', 'license_key',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agency', 'license_key',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('agency', 'email_api_key')
    op.drop_column('agency', 'sms_api_key')
    # ### end Alembic commands ###
