"""add alert_threshold to user

Revision ID: 7c738a4cda96
Revises: 2451d1770fd3
Create Date: 2026-04-03 20:28:48.877067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c738a4cda96'
down_revision: Union[str, Sequence[str], None] = '2451d1770fd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add column as nullable first
    op.add_column('user', sa.Column('alert_threshold', sa.Integer(), nullable=True))
    
    # Set default value for existing rows
    op.execute("UPDATE \"user\" SET alert_threshold = 8")
    
    # Make it NOT NULL
    op.alter_column('user', 'alert_threshold', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'alert_threshold')
    # ### end Alembic commands ###
