"""add_demo_fields_lead_notification

Revision ID: 82e92e77ba07
Revises: 06f05fe2bd0a
Create Date: 2026-04-19 16:20:42.569447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82e92e77ba07'
down_revision: Union[str, Sequence[str], None] = '06f05fe2bd0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agency', sa.Column('license_key', sa.String(), nullable=True))
    op.add_column('agency', sa.Column('last_heartbeat', sa.DateTime(), nullable=True))
    op.add_column('agency', sa.Column('expires_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_agency_license_key'), 'agency', ['license_key'], unique=True)
    op.add_column('lead', sa.Column('notes', sa.String(), nullable=True))
    op.add_column('lead', sa.Column('score_chaleur', sa.Integer(), nullable=False, server_default='5'))
    op.alter_column('notification', 'deal_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notification', 'deal_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('lead', 'score_chaleur')
    op.drop_column('lead', 'notes')
    op.drop_index(op.f('ix_agency_license_key'), table_name='agency')
    op.drop_column('agency', 'expires_at')
    op.drop_column('agency', 'last_heartbeat')
    op.drop_column('agency', 'license_key')
    # end Alembic commands
    # ### end Alembic commands ###
